### ISSUE TITLE
`valset`: Optimize VALIDATORS storage

### ISSUE THREAD

**Issue by ethanfrey** [confio/poe-contracts#42]
They store 

```rust
pub struct ValidatorInfo {
    /// TODO: better name to specify this is the Tendermint pubkey for consensus?
    pub validator_pubkey: Pubkey,
    pub operator: Addr,
    pub metadata: ValidatorMetadata,
    /// The voting power in Tendermint sdk
    pub power: u64,
}
```

for each one in an `Item<Vec<ValidatorInfo>>`. I think we need to keep an eye on the footprint (max 128kb stored under one key enforced by cosmwasm-vm). Let's look at better ways of storing this, to efficiently read all (for a diff) as well as not blowing up disk space too much.

We may go to a Map based approach, but let's do research

**Comment by ethanfrey** [comment]
Look at #35 as one approach. Let's research and consider more

**Comment by ethanfrey** [comment]
@maurolacy can you research the size of said structure?

Also, which fields are constant and which change? Maybe we can store the constant in a Map and use just the keys in `Item<Vec<_>>` so we can quickly calculate the diff in memory and only do storage access for the (relatively few) validators that changed.

**Comment by ethanfrey** [comment]
Assumption: we have 100-300 validators in the active set. The number that change in one epoch will be quite small (say 1-10). If we can limit "expensive" storage access to just the diff, this would be a nice improvement.

**Comment by maurolacy** [comment]
The problem here that we're storing `ValidatorMetadada`, which has `String` fields, inside `ValidatorInfo`. This should clearly be moved to a `Map` structure or similar. Then, we can consider limiting those fields to reasonable values. The only field currently being validated is moniker, and for a min value, not a max value.

After removing `ValidatorMetadata`, `ValidatorInfo` is left  with 64 bytes for the structure. That, plus 33 bytes for the pubkey, and 45 bytes for the address, gives us 134 bytes.

128 Kbytes / 134 bytes ~= 900 entries, which would be fine for all purposes.

So, the issue here is removing the potentially unlimited `ValidatorMetadata` from `ValidatorInfo`. A full `Map` approach for `ValidatorInfo` would also solve this. But I think keeping with the current structure is simpler / less disruptive.

**Comment by ethanfrey** [comment]
If I understand, we pull out ValidatorMetadata to it's own Map (indexed by Operator addr?), and otherwise keep the same structure, now that the ValidatorInfo in the `Item<Vec<_>>` is smaller.

Did you check the JSON-encoded size? "45 bytes for the address" ,must also include `"address":"cosmos1jhjh.....",` right?

**Comment by maurolacy** [comment]
> If I understand, we pull out ValidatorMetadata to it's own Map (indexed by Operator addr?), and otherwise keep the same structure, now that the ValidatorInfo in the `Item<Vec<_>>` is smaller.

That's the idea, yes.

> 
> Did you check the JSON-encoded size? "45 bytes for the address" ,must also include `"address":"cosmos1jhjh.....",` right?

I used `mem:size_of()` and included the address / pubkey lengths. But I think you are right: these things are stored serialized, rithgt? So, they actually take more space for the formatting.

Working on this right now. Will get better estimates, and an integration test for checking `Item` limits.
